# -*- coding: utf-8 -*-

PLAYERS = {
	9: "Soy sauce",
	42: "Pocket Aces",
	21: "Loop:",
	13: "roBAst",
	17: "sigpoker",
	48: "AHhHhHHHhhhhhHHHHHhhHHH!",
	31: "TricksAreForKids",
	38: "The Letter D",
	12: "I Ran Into A Tree When I Was Younger",
	8: "Vampire_cards",
	18: "PhOwls",
	41: "Five? - Good Night Everyone!",
	23: "code_tigers",
	25: "victors of the west heroes",
	44: "Medium Pepsi",
	35: "So Code. Much Compiled.",
	34: "Octothorpus",
	7: "Snow",
	45: "The B Team",
	11: "Land Whale Shark",
	19: "Cuda Doge",
	20: "Brickbot",
	46: "Gargantuan Balls",
	32: "̶SPΔ̸CΞ ̸CO̸NTRO̸L",
	47: "card_minnow",
	43: "Anti_Doge_Crusader",
	28: "qwerty",
	16: "▲▲▼▼◄►◄►B A St",
	26: "Altos",
	10: "trey burke",
	24: "The Luddites",
	14: "Andy",
	6: "Farmer John",
	27: "CSMXX",
	39: "Little Bobby Tables",
	37: "JinKeLa",
	22: "The Michael J. Fox Martini Shakers",
	15: "Free The Mallocs",
	5: "UNIQUE SN❄WFLAKES",
	36: "The Yoopers",
	40: "Potato",
	30: "all your base are belong to us",
	33: "Jack of Spades",
	29: "kxpq",
}